raid:
  cooldown_hours: 168
  long_stream_hours: 2.0
channels:
- name: traveldanielle
  priority: 3
- name: poopernoodle
  priority: 3
- name: luality
  priority: 1
- name: highrollersdnd
  priority: 1
- name: marabunny
  priority: 1
- name: eliseteria
  priority: 3
- name: parkenharbor
  priority: 3
- name: lilaggy
  priority: 3
- name: ipaintbirbs
  priority: 3
- name: foomia
  priority: 1
- name: tracywiles
  priority: 1
- name: theosolomon1
  priority: 2
